services:
  - type: web
    name: cardiosignal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "gunicorn app:app"
    healthCheckPath: /healthz
